all:
  hosts:
    node1:
      ansible_host: 192.168.10.10
      ip: 192.168.10.10
      access_ip: 192.168.10.10
    node2:
      ansible_host: 192.168.20.20
      ip: 192.168.20.20
      access_ip: 192.168.20.20
    node3:
      ansible_host: 192.168.30.30
      ip: 192.168.30.30
      access_ip: 192.168.30.30
    node4:
      ansible_host: 192.168.40.40
      ip: 192.168.40.40
      access_ip: 192.168.40.40
  children:
    kube_control_plane:
      hosts:
        node1:

    kube_node:
      hosts:
        node1:
        node2:
        node3:
        node4:
    etcd:
      hosts:
        node1:


    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
